/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vugbcvncjfuwgcuhhowy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ1Z2Jjdm5jamZ1d2djdWhob3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5NTAwNjQsImV4cCI6MjA4NTUyNjA2NH0.hj4oMM0F9LlHjV-_Wh0Otm4M5W7IW9-0qVAf-mXZp3c"